spring.application.name=fantasy-basket-service


springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.swagger-ui.enabled=true
springdoc.api-docs.swagger-ui.path=/swagger-ui.html

# Nastavení pro na?tení externího OpenAPI YAML souboru
springdoc.api-docs.open-api-spec-location=classpath:/openapi.yml